project:
  type: website
  output-dir: docs

website:
  title: "FinalProject378Durocher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - eda.qmd
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
